.class public interface abstract Lcom/fengeek/styleview/c/a;
.super Ljava/lang/Object;
.source "AxisValueFormatter.java"


# virtual methods
.method public abstract formatValueForAutoGeneratedAxis([CFI)I
.end method

.method public abstract formatValueForManualAxis([CLcom/fengeek/styleview/model/c;)I
.end method
