.class public Lcom/fengeek/styleview/c/f;
.super Ljava/lang/Object;
.source "SimpleAxisValueFormatter.java"

# interfaces
.implements Lcom/fengeek/styleview/c/a;


# instance fields
.field private a:Lcom/fengeek/styleview/c/k;


# direct methods
.method public constructor <init>()V
    .locals 1

    .line 9
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 7
    new-instance v0, Lcom/fengeek/styleview/c/k;

    invoke-direct {v0}, Lcom/fengeek/styleview/c/k;-><init>()V

    iput-object v0, p0, Lcom/fengeek/styleview/c/f;->a:Lcom/fengeek/styleview/c/k;

    .line 10
    iget-object v0, p0, Lcom/fengeek/styleview/c/f;->a:Lcom/fengeek/styleview/c/k;

    invoke-virtual {v0}, Lcom/fengeek/styleview/c/k;->determineDecimalSeparator()V

    return-void
.end method

.method public constructor <init>(I)V
    .locals 1

    .line 14
    invoke-direct {p0}, Lcom/fengeek/styleview/c/f;-><init>()V

    .line 15
    iget-object v0, p0, Lcom/fengeek/styleview/c/f;->a:Lcom/fengeek/styleview/c/k;

    invoke-virtual {v0, p1}, Lcom/fengeek/styleview/c/k;->setDecimalDigitsNumber(I)Lcom/fengeek/styleview/c/k;

    return-void
.end method


# virtual methods
.method public formatValueForAutoGeneratedAxis([CFI)I
    .locals 1

    .line 27
    iget-object v0, p0, Lcom/fengeek/styleview/c/f;->a:Lcom/fengeek/styleview/c/k;

    invoke-virtual {v0, p1, p2, p3}, Lcom/fengeek/styleview/c/k;->formatFloatValueWithPrependedAndAppendedText([CFI)I

    move-result p1

    return p1
.end method

.method public formatValueForManualAxis([CLcom/fengeek/styleview/model/c;)I
    .locals 2

    .line 20
    iget-object v0, p0, Lcom/fengeek/styleview/c/f;->a:Lcom/fengeek/styleview/c/k;

    .line 21
    invoke-virtual {p2}, Lcom/fengeek/styleview/model/c;->getValue()F

    move-result v1

    invoke-virtual {p2}, Lcom/fengeek/styleview/model/c;->getLabelAsChars()[C

    move-result-object p2

    .line 20
    invoke-virtual {v0, p1, v1, p2}, Lcom/fengeek/styleview/c/k;->formatFloatValueWithPrependedAndAppendedText([CF[C)I

    move-result p1

    return p1
.end method

.method public getAppendedText()[C
    .locals 1

    .line 42
    iget-object v0, p0, Lcom/fengeek/styleview/c/f;->a:Lcom/fengeek/styleview/c/k;

    invoke-virtual {v0}, Lcom/fengeek/styleview/c/k;->getAppendedText()[C

    move-result-object v0

    return-object v0
.end method

.method public getDecimalDigitsNumber()I
    .locals 1

    .line 33
    iget-object v0, p0, Lcom/fengeek/styleview/c/f;->a:Lcom/fengeek/styleview/c/k;

    invoke-virtual {v0}, Lcom/fengeek/styleview/c/k;->getDecimalDigitsNumber()I

    move-result v0

    return v0
.end method

.method public getDecimalSeparator()C
    .locals 1

    .line 60
    iget-object v0, p0, Lcom/fengeek/styleview/c/f;->a:Lcom/fengeek/styleview/c/k;

    invoke-virtual {v0}, Lcom/fengeek/styleview/c/k;->getDecimalSeparator()C

    move-result v0

    return v0
.end method

.method public getPrependedText()[C
    .locals 1

    .line 51
    iget-object v0, p0, Lcom/fengeek/styleview/c/f;->a:Lcom/fengeek/styleview/c/k;

    invoke-virtual {v0}, Lcom/fengeek/styleview/c/k;->getPrependedText()[C

    move-result-object v0

    return-object v0
.end method

.method public setAppendedText([C)Lcom/fengeek/styleview/c/f;
    .locals 1

    .line 46
    iget-object v0, p0, Lcom/fengeek/styleview/c/f;->a:Lcom/fengeek/styleview/c/k;

    invoke-virtual {v0, p1}, Lcom/fengeek/styleview/c/k;->setAppendedText([C)Lcom/fengeek/styleview/c/k;

    return-object p0
.end method

.method public setDecimalDigitsNumber(I)Lcom/fengeek/styleview/c/f;
    .locals 1

    .line 37
    iget-object v0, p0, Lcom/fengeek/styleview/c/f;->a:Lcom/fengeek/styleview/c/k;

    invoke-virtual {v0, p1}, Lcom/fengeek/styleview/c/k;->setDecimalDigitsNumber(I)Lcom/fengeek/styleview/c/k;

    return-object p0
.end method

.method public setDecimalSeparator(C)Lcom/fengeek/styleview/c/f;
    .locals 1

    .line 64
    iget-object v0, p0, Lcom/fengeek/styleview/c/f;->a:Lcom/fengeek/styleview/c/k;

    invoke-virtual {v0, p1}, Lcom/fengeek/styleview/c/k;->setDecimalSeparator(C)Lcom/fengeek/styleview/c/k;

    return-object p0
.end method

.method public setPrependedText([C)Lcom/fengeek/styleview/c/f;
    .locals 1

    .line 55
    iget-object v0, p0, Lcom/fengeek/styleview/c/f;->a:Lcom/fengeek/styleview/c/k;

    invoke-virtual {v0, p1}, Lcom/fengeek/styleview/c/k;->setPrependedText([C)Lcom/fengeek/styleview/c/k;

    return-object p0
.end method
